# Generated by Django 2.2.14 on 2020-07-31 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='tests',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customtext_tests', to='home.CustomText'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='user2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homepage_user2', to='home.CustomText'),
        ),
    ]
